vim.o.encoding="utf-8"
vim.o.exrc = true
vim.o.relativenumber = true
vim.o.number = true
vim.o.hlsearch = false
vim.o.hidden = true
vim.o.errorbells = false
vim.o.belloff = "all"
vim.o.tabstop = 4
vim.o.softtabstop = 4
vim.o.expandtab = true
vim.o.wrap = false
vim.o.swapfile = false
vim.o.backup = false
vim.o.undodir = "~/.vim/undodir"
vim.o.incsearch = true
vim.o.scrolloff = 8
vim.o.signcolumn = "yes"
vim.o.pastetoggle="<F3>"

