prompt = "starship prompt"

startup = [
    "let oldpath = (pathvar)",
    "let-env PATH = (pathvar | where ( $it | str starts-with \"/mnt\" ) == $false | str collect \":\" )",

   "alias a = paru",
   "alias as = paru -S"
]
