format = "$directory$git_branch$python$git_state$git_status$status"
add_newline = false

[git_branch]
symbol = " "

[python]
symbol = " "

[status]
disabled = false

[directory]
truncation_length = 8

